apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-1
spec:
  tasks:
    - name: run-1
      taskRef:
        kind: Task
        name: task-1
    - name: run-2
      runAfter:
        - run-1
      taskRef:
        kind: Task
        name: task-2
  workspaces:
    - name: workspace
