---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data-002
  namespace: project-backend
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
